# Generated by Django 2.0.7 on 2020-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phone_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('Stream', models.CharField(max_length=40)),
                ('identity', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_id',
            field=models.CharField(max_length=20),
        ),
    ]
